name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: ku1
      run: sudo add-apt-repository main
    - name: ku2
      run: sudo add-apt-repository universe
    - name: ku3   
      run: sudo add-apt-repository restricted
    - name: ku4
      run: sudo add-apt-repository multiverse  
    
    - name: apt update
      run: sudo apt update
      
    - name: apt list --upgradable
      run: sudo apt list --upgradable

    - name: In order to build aria2 from the source package, you need following development packages (package name may vary depending on the distribution you use)
      run: sudo apt install libssl-dev libssh2-1-dev libc-ares-dev libxml2-dev zlib1g-dev libsqlite3-dev pkg-config -y
      
    - name: If you downloaded source code from git repository, you have to install following packages to get autoconf macros
      run: sudo apt install libxml2-dev libcppunit-dev autoconf automake autotools-dev autopoint libtool -y

    - name: And run following command to generate configure script and other files necessary to build the program
      run: autoreconf -i

    - name: The quickest way to build aria2 is first run configure script
      run: ./configure ARIA2_STATIC=yes

#    - name: To build statically linked aria2, use ARIA2_STATIC=yes command-line option
#      run: ./configure
      
    - name: After configuration is done, run make to compile the program
      run: make -j4
      
    - name: b
      run: make -s -n install -o all \

#    - name: ku5
#      run: sudo apt-get install build-essential fakeroot dpkg-dev

#    - name: build
#      run: dpkg-buildpackage -rfakeroot -b
      
#    - name: install
#      run: make install  
      
    - uses: actions/upload-artifact@v3
      with:
       name: my-artifact
       path: /home/runner/work/aria2-bulid/aria2-bulid/
